version: '3.8'

# Define services
services:
  database:
    container_name: "database"
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  redis:
    container_name: "redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - fullstack
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    networks:
      - fullstack
    volumes:
      - ./rabbit-mq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - ${RABBITMQ_PORT}:5672
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile
    ports:
      - ${PORT}:8080
    depends_on:
      - database
      - rabbitmq
      - redis
    stdin_open: true
    tty: true
    networks:
      - fullstack
    env_file:
      - .env
# Define volumes
volumes:
  database_postgres:

# Define networks
networks:
  fullstack:
    driver: bridge
